apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pocketshortener
commonLabels:
  app: pocketshortener-ps
resources:
- ps-deployment.yaml
- ps-service.yaml
- cloudflared.yaml
secretGenerator:
- name: db-user-pass
  envs:
  - .env.password
configMapGenerator:
- name: psconfig
  literals:
  - UN=james@clarkezone.net
  - URL=https://pocket-shortner-stage.dev.clarkezone.dev/
  - URLold=http://pocketbase-service.pocketshortener.svc.cluster.local:8080/
    
