apiVersion: apps/v1
kind: Deployment
metadata:
  name: ps-deployment
  labels:
    app: pocketshortener-ps
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: pocketshortener-ps
  template:
    metadata:
      labels:
        app: pocketshortener-ps
    spec:
      containers:
      - name: pocketbase
        image: registry.dev.clarkezone.dev/pocketshortenp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
          - name: POCKET_SHORTEN_USERNAME
            valueFrom:
              configMapKeyRef:
                name: psconfig
                key: UN
          - name: POCKET_DB_URL
            valueFrom:
              configMapKeyRef:
                name: psconfig
                key: URL
          - name: POCKET_SHORTEN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-user-pass
                key: PW
