package main

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/go-resty/resty/v2"
)

type authresponse struct {
	Admin string `json:"-"`
	Token string
}

type AutoGenerated struct {
	Page       int `json:"page"`
	PerPage    int `json:"perPage"`
	TotalItems int `json:"totalItems"`
	TotalPages int `json:"totalPages"`
	Items      []struct {
		CollectionID   string `json:"@collectionId"`
		CollectionName string `json:"@collectionName"`
		Created        string `json:"created"`
		Field1         string `json:"field1"`
		ID             string `json:"id"`
		Updated        string `json:"updated"`
	} `json:"items"`
}

func main() {
	user := os.Getenv("POCKET_SHORTEN_USERNAME")
	pass := os.Getenv("POCKET_SHORTEN_PASSWORD")

	client := resty.New()

	resp, err := client.R().
		SetQueryParams(map[string]string{
			"page_no": "1",
		}).
		SetHeader("Accept", "application/json").
		SetHeader("Content-Type", "application/json").
		SetBody(`{"email":"` + user + `", "password":"` + pass + `"}`).
		Post("http://clarkezonedevbox3-tr:9099/api/admins/auth-via-email")

	if err != nil {
		panic(err)
	}

	dresp := authresponse{}
	err = json.Unmarshal(resp.Body(), &dresp)
	if err != nil {
		panic(err)
	}
	fmt.Println(dresp.Token)

	resp, err = client.R().
		SetQueryParams(map[string]string{
			"page_no": "1",
		}).
		SetHeader("Accept", "application/json").
		SetHeader("Authorization", "Admin "+dresp.Token).
		Get("http://clarkezonedevbox3-tr:9099/api/collections/urls/records")
	fmt.Println("Response Info:")
	fmt.Println("  Error      :", err)
	fmt.Println("  Status Code:", resp.StatusCode())
	fmt.Println("  Status     :", resp.Status())
	fmt.Println("  Proto      :", resp.Proto())
	fmt.Println("  Time       :", resp.Time())
	fmt.Println("  Received At:", resp.ReceivedAt())
	fmt.Println("  Body       :\n", resp)

	dresp2 := AutoGenerated{}
	err = json.Unmarshal(resp.Body(), &dresp2)
	if err != nil {
		panic(err)
	}
	fmt.Println(dresp2.Items[0].Field1)
	fmt.Println(dresp2.Items[1].Field1)
}
